index:
  path: /
  controller: App\Controller\PageController::index

vue:
  path: /vue
  controller: App\Controller\PageController::vue

get:
  path: /api/get
  controller: App\Controller\ApiController::getjson
